const sb=supabaseClient;
const loginBox=document.getElementById("loginBox"), panel=document.getElementById("panel"), loginMsg=document.getElementById("loginMsg");
async function check(){const {data}=await sb.auth.getSession(); if(data.session){loginBox.classList.add("hidden");panel.classList.remove("hidden");loadAll()}else{loginBox.classList.remove("hidden");panel.classList.add("hidden")}}
document.getElementById("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();loginMsg.textContent="Ingresando...";const {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});loginMsg.textContent=error?error.message:"";if(!error)check()});
document.getElementById("logout")?.addEventListener("click",async()=>{await sb.auth.signOut();check()});
programForm?.addEventListener("submit",async e=>{e.preventDefault();const {error}=await sb.from("programacion").insert({fecha:pFecha.value,titulo:pTitulo.value,hora_inicio:pInicio.value,hora_fin:pFin.value,descripcion:pDesc.value});alert(error?error.message:"Programa guardado.");if(!error){e.target.reset();loadPrograms()}});
newsForm?.addEventListener("submit",async e=>{e.preventDefault();const {error}=await sb.from("noticias").insert({titulo:nTitulo.value,categoria:nCategoria.value,resumen:nResumen.value,contenido:nContenido.value,imagen_url:nImagen.value,video_url:nVideo.value});alert(error?error.message:"Noticia publicada.");if(!error){e.target.reset();loadNewsAdmin()}});
adForm?.addEventListener("submit",async e=>{e.preventDefault();const {error}=await sb.from("publicidad").insert({titulo:aTitulo.value,descripcion:aDesc.value,imagen_url:aImagen.value});alert(error?error.message:"Publicidad publicada.");if(!error){e.target.reset();loadAdsAdmin()}});
async function loadPrograms(){const {data}=await sb.from("programacion").select("*").order("fecha",{ascending:false}).order("hora_inicio");programList.innerHTML=(data||[]).map(x=>`<div class="admin-row"><span><b>${x.fecha}</b> · ${x.hora_inicio}-${x.hora_fin} · ${x.titulo}</span><button class="admin-btn secondary" onclick="del('programacion','${x.id}',loadPrograms)">Eliminar</button></div>`).join("")}
async function loadNewsAdmin(){const {data}=await sb.from("noticias").select("*").order("created_at",{ascending:false});newsList.innerHTML=(data||[]).map(x=>`<div class="admin-row"><span><b>${x.titulo}</b><br>${x.categoria||""}</span><button class="admin-btn secondary" onclick="del('noticias','${x.id}',loadNewsAdmin)">Eliminar</button></div>`).join("")}
async function loadAdsAdmin(){const {data}=await sb.from("publicidad").select("*").order("created_at",{ascending:false});adList.innerHTML=(data||[]).map(x=>`<div class="admin-row"><span><b>${x.titulo}</b></span><button class="admin-btn secondary" onclick="del('publicidad','${x.id}',loadAdsAdmin)">Eliminar</button></div>`).join("")}
async function del(table,id,cb){if(confirm("¿Eliminar este elemento?")){const {error}=await sb.from(table).delete().eq("id",id);if(error)alert(error.message);else cb()}}
function loadAll(){loadPrograms();loadNewsAdmin();loadAdsAdmin()}
check();
